apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  DATABASE_URL: "postgres://kreise:{{ required "app.postgresPassword required" .Values.app.postgresPassword }}@{{ .Release.Name }}-postgres:5432/kreise?sslmode=disable"
  POSTGRES_PASSWORD: {{ required "app.postgresPassword required" .Values.app.postgresPassword | quote }}
  TOKEN_SIGNING_KEY: {{ required "app.tokenSigningKey required" .Values.app.tokenSigningKey | quote }}
  PUBLIC_BASE_URL: "https://{{ .Values.ingress.host }}"
  APP_ENV: "prod"
  APP_ADDR: ":8080"
  LOG_LEVEL: "info"
  MAIL_FROM: {{ .Values.app.mailFrom | quote }}
  MAIL_FROM_DISPLAY_NAME: {{ .Values.app.mailFromDisplayName | quote }}
  MAIL_UNSUBSCRIBE_ADDRESS: {{ .Values.app.mailUnsubscribeAddress | quote }}
  AWS_REGION: {{ .Values.app.awsRegion | quote }}
  SES_CONFIGURATION_SET: {{ .Values.app.sesConfigurationSet | quote }}
  STORAGE_ENDPOINT: "http://{{ .Release.Name }}-minio:9000"
  STORAGE_REGION: "us-east-1"
  STORAGE_BUCKET: "kreise"
  STORAGE_ACCESS_KEY: {{ required "app.minioAccessKey required" .Values.app.minioAccessKey | quote }}
  STORAGE_SECRET_KEY: {{ required "app.minioSecretKey required" .Values.app.minioSecretKey | quote }}
  STORAGE_USE_PATH_STYLE: "true"
