// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (actor_user_id, event_id, action, target_kind, target_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	ActorUserID *uuid.UUID
	EventID     *uuid.UUID
	Action      string
	TargetKind  string
	TargetID    *string
	Payload     []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorUserID,
		arg.EventID,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Payload,
	)
	return err
}

const listAuditForEvent = `-- name: ListAuditForEvent :many
SELECT id, actor_user_id, event_id, action, target_kind, target_id, payload, created_at FROM audit_log
WHERE event_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditForEventParams struct {
	EventID *uuid.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListAuditForEvent(ctx context.Context, arg ListAuditForEventParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditForEvent, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.EventID,
			&i.Action,
			&i.TargetKind,
			&i.TargetID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
