// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelBookingAndTickets = `-- name: CancelBookingAndTickets :exec
WITH booking_update AS (
    UPDATE bookings SET status = 'canceled', canceled_at = now()
    WHERE bookings.id = $1 AND bookings.status <> 'canceled'
    RETURNING bookings.id AS booking_id
)
UPDATE tickets SET status = 'canceled', canceled_at = now()
WHERE tickets.booking_id = (SELECT booking_id FROM booking_update)
`

// Marks the booking and all its tickets as canceled in one statement.
// Used by the sweeper and by ticket-cancel handlers in Phase 5.
func (q *Queries) CancelBookingAndTickets(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelBookingAndTickets, id)
	return err
}

const countActiveSeatsForEvent = `-- name: CountActiveSeatsForEvent :one
SELECT count(*)::int AS seats
FROM tickets
WHERE event_id = $1 AND status IN ('booked', 'paid', 'checked_in')
`

// Counts tickets that consume a seat. Canceled tickets do not consume.
// BOOKED tickets count even if reservation isn't paid yet — capacity must
// account for in-flight bookings or two parallel bookings could both succeed
// past the limit.
func (q *Queries) CountActiveSeatsForEvent(ctx context.Context, eventID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveSeatsForEvent, eventID)
	var seats int32
	err := row.Scan(&seats)
	return seats, err
}

const countActiveSeatsForEventLocking = `-- name: CountActiveSeatsForEventLocking :one
WITH locked AS (
    SELECT events.id AS event_id FROM events WHERE events.id = $1 FOR UPDATE
)
SELECT count(*)::int AS seats
FROM tickets, locked
WHERE tickets.event_id = locked.event_id
  AND tickets.status IN ('booked', 'paid', 'checked_in')
`

// Same as above but takes a row-level lock on the events row first to
// serialize concurrent bookings. Used inside the booking transaction.
func (q *Queries) CountActiveSeatsForEventLocking(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveSeatsForEventLocking, id)
	var seats int32
	err := row.Scan(&seats)
	return seats, err
}

const countSearchBookingsForEvent = `-- name: CountSearchBookingsForEvent :one
SELECT
    count(*)::int                                                    AS total_count,
    count(*) FILTER (WHERE b.status = 'paid')::int                   AS paid_count,
    count(*) FILTER (WHERE b.status = 'booked')::int                 AS booked_count,
    count(*) FILTER (WHERE b.status = 'canceled')::int               AS canceled_count,
    COALESCE(sum(
        CASE
            WHEN b.status = 'paid'
                AND COALESCE(b.payment_method, '') NOT IN ('donation', 'at_door')
            THEN b.total_amount_minor
            ELSE 0
        END
        +
        CASE
            WHEN b.status = 'paid'
            THEN COALESCE((
                SELECT SUM(t.paid_amount_minor)::bigint
                FROM tickets t
                WHERE t.booking_id = b.id AND t.paid_amount_minor IS NOT NULL
            ), 0)
            ELSE 0
        END
    ), 0)::bigint AS paid_revenue_minor,
    COALESCE(sum((SELECT count(*) FROM participants WHERE booking_id = b.id)::int), 0)::int                                   AS total_participants,
    COALESCE(sum((SELECT count(*) FROM participants WHERE booking_id = b.id)::int) FILTER (WHERE b.status = 'paid'), 0)::int  AS paid_participants,
    COALESCE(sum((SELECT count(*) FROM participants WHERE booking_id = b.id)::int) FILTER (WHERE b.status = 'booked'), 0)::int AS booked_participants
FROM bookings b
WHERE b.event_id = $1
  AND ($2::text IS NULL OR b.status = $2::text)
  AND ($3::text IS NULL OR b.payment_method = $3::text)
  AND ($4::timestamptz IS NULL OR b.created_at >= $4::timestamptz)
  AND ($5::timestamptz   IS NULL OR b.created_at <  $5::timestamptz)
  AND ($6::text IS NULL OR
       lower(b.contact_email) LIKE '%' || lower($6::text) || '%' OR
       lower(b.contact_name)  LIKE '%' || lower($6::text) || '%' OR
       upper(substring(replace(b.id::text, '-', '') from 1 for 8)) LIKE upper('%' || $6::text || '%'))
`

type CountSearchBookingsForEventParams struct {
	EventID       uuid.UUID
	Status        *string
	PaymentMethod *string
	FromTs        *time.Time
	ToTs          *time.Time
	Q             *string
}

type CountSearchBookingsForEventRow struct {
	TotalCount         int32
	PaidCount          int32
	BookedCount        int32
	CanceledCount      int32
	PaidRevenueMinor   int64
	TotalParticipants  int32
	PaidParticipants   int32
	BookedParticipants int32
}

// Matches SearchBookingsForEvent filters minus pagination/sort. Used for the
// total row count and the summary strip.
// Revenue formula (real money received, not "suggested totals"):
//
//	pre_paid_revenue  = SUM(booking.total_amount_minor) for paid bookings
//	                    whose payment_method is NOT in ('donation', 'at_door')
//	                    — these were collected via bank transfer / PayPal /
//	                      test mode upfront, so the booking total IS the
//	                      money received.
//
//	door_revenue      = SUM(ticket.paid_amount_minor) over the tickets of
//	                    paid bookings — populated by the door scanner at
//	                    check-in. For at-door / donation bookings this is
//	                    the ONLY source of real money (booking.total_minor
//	                    was the suggested / expected amount, not what
//	                    actually got handed over). For pre-paid bookings
//	                    the column stays NULL and contributes nothing.
//
//	revenue_minor     = pre_paid_revenue + door_revenue
//
// The participant_count subquery is duplicated rather than joined to avoid
// multiplying the per-booking sums by the participant count.
func (q *Queries) CountSearchBookingsForEvent(ctx context.Context, arg CountSearchBookingsForEventParams) (CountSearchBookingsForEventRow, error) {
	row := q.db.QueryRow(ctx, countSearchBookingsForEvent,
		arg.EventID,
		arg.Status,
		arg.PaymentMethod,
		arg.FromTs,
		arg.ToTs,
		arg.Q,
	)
	var i CountSearchBookingsForEventRow
	err := row.Scan(
		&i.TotalCount,
		&i.PaidCount,
		&i.BookedCount,
		&i.CanceledCount,
		&i.PaidRevenueMinor,
		&i.TotalParticipants,
		&i.PaidParticipants,
		&i.BookedParticipants,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    event_id, contact_email, contact_name, contact_phone, locale,
    status, total_amount_minor, currency, coupon_id, payment_method,
    payment_reference, reservation_expires_at, paid_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, event_id, contact_email, contact_name, contact_phone, locale, status, total_amount_minor, currency, coupon_id, payment_method, payment_reference, reservation_expires_at, created_at, paid_at, canceled_at
`

type CreateBookingParams struct {
	EventID              uuid.UUID
	ContactEmail         string
	ContactName          string
	ContactPhone         *string
	Locale               string
	Status               string
	TotalAmountMinor     int64
	Currency             string
	CouponID             *uuid.UUID
	PaymentMethod        *string
	PaymentReference     *string
	ReservationExpiresAt *time.Time
	PaidAt               *time.Time
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.EventID,
		arg.ContactEmail,
		arg.ContactName,
		arg.ContactPhone,
		arg.Locale,
		arg.Status,
		arg.TotalAmountMinor,
		arg.Currency,
		arg.CouponID,
		arg.PaymentMethod,
		arg.PaymentReference,
		arg.ReservationExpiresAt,
		arg.PaidAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ContactEmail,
		&i.ContactName,
		&i.ContactPhone,
		&i.Locale,
		&i.Status,
		&i.TotalAmountMinor,
		&i.Currency,
		&i.CouponID,
		&i.PaymentMethod,
		&i.PaymentReference,
		&i.ReservationExpiresAt,
		&i.CreatedAt,
		&i.PaidAt,
		&i.CanceledAt,
	)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO participants (event_id, booking_id, name, email, newsletter_optin, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_id, booking_id, name, email, newsletter_optin, notes, created_at
`

type CreateParticipantParams struct {
	EventID         uuid.UUID
	BookingID       uuid.UUID
	Name            string
	Email           *string
	NewsletterOptin bool
	Notes           *string
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.EventID,
		arg.BookingID,
		arg.Name,
		arg.Email,
		arg.NewsletterOptin,
		arg.Notes,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.BookingID,
		&i.Name,
		&i.Email,
		&i.NewsletterOptin,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    id, booking_id, participant_id, event_id, status, qr_token, qr_nonce,
    phase_id, category_id, duration_id, amount_minor, paid_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, booking_id, participant_id, event_id, status, qr_token, phase_id, category_id, duration_id, amount_minor, created_at, paid_at, canceled_at, checked_in_at, qr_nonce, paid_amount_minor
`

type CreateTicketParams struct {
	ID            uuid.UUID
	BookingID     uuid.UUID
	ParticipantID uuid.UUID
	EventID       uuid.UUID
	Status        string
	QrToken       string
	QrNonce       []byte
	PhaseID       *uuid.UUID
	CategoryID    *uuid.UUID
	DurationID    *uuid.UUID
	AmountMinor   int64
	PaidAt        *time.Time
}

// id is supplied by the caller so qr_token (HMAC over ticket id + nonce)
// can be precomputed before the INSERT.
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ID,
		arg.BookingID,
		arg.ParticipantID,
		arg.EventID,
		arg.Status,
		arg.QrToken,
		arg.QrNonce,
		arg.PhaseID,
		arg.CategoryID,
		arg.DurationID,
		arg.AmountMinor,
		arg.PaidAt,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ParticipantID,
		&i.EventID,
		&i.Status,
		&i.QrToken,
		&i.PhaseID,
		&i.CategoryID,
		&i.DurationID,
		&i.AmountMinor,
		&i.CreatedAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CheckedInAt,
		&i.QrNonce,
		&i.PaidAmountMinor,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, event_id, contact_email, contact_name, contact_phone, locale, status, total_amount_minor, currency, coupon_id, payment_method, payment_reference, reservation_expires_at, created_at, paid_at, canceled_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ContactEmail,
		&i.ContactName,
		&i.ContactPhone,
		&i.Locale,
		&i.Status,
		&i.TotalAmountMinor,
		&i.Currency,
		&i.CouponID,
		&i.PaymentMethod,
		&i.PaymentReference,
		&i.ReservationExpiresAt,
		&i.CreatedAt,
		&i.PaidAt,
		&i.CanceledAt,
	)
	return i, err
}

const listBookingsForEvent = `-- name: ListBookingsForEvent :many
SELECT b.id, b.event_id, b.contact_email, b.contact_name, b.contact_phone,
       b.locale, b.status, b.total_amount_minor, b.currency, b.coupon_id,
       b.payment_method, b.payment_reference, b.reservation_expires_at,
       b.created_at, b.paid_at, b.canceled_at,
       COUNT(p.id)::int AS participant_count
FROM bookings b
LEFT JOIN participants p ON p.booking_id = b.id
WHERE b.event_id = $1
GROUP BY b.id
ORDER BY b.created_at DESC
`

type ListBookingsForEventRow struct {
	ID                   uuid.UUID
	EventID              uuid.UUID
	ContactEmail         string
	ContactName          string
	ContactPhone         *string
	Locale               string
	Status               string
	TotalAmountMinor     int64
	Currency             string
	CouponID             *uuid.UUID
	PaymentMethod        *string
	PaymentReference     *string
	ReservationExpiresAt *time.Time
	CreatedAt            time.Time
	PaidAt               *time.Time
	CanceledAt           *time.Time
	ParticipantCount     int32
}

// Kept for backwards compat with code that doesn't yet use the filtered
// variant. New callers should use SearchBookingsForEvent.
func (q *Queries) ListBookingsForEvent(ctx context.Context, eventID uuid.UUID) ([]ListBookingsForEventRow, error) {
	rows, err := q.db.Query(ctx, listBookingsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsForEventRow{}
	for rows.Next() {
		var i ListBookingsForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ContactEmail,
			&i.ContactName,
			&i.ContactPhone,
			&i.Locale,
			&i.Status,
			&i.TotalAmountMinor,
			&i.Currency,
			&i.CouponID,
			&i.PaymentMethod,
			&i.PaymentReference,
			&i.ReservationExpiresAt,
			&i.CreatedAt,
			&i.PaidAt,
			&i.CanceledAt,
			&i.ParticipantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpandedBookingsForEvent = `-- name: ListExpandedBookingsForEvent :many
SELECT b.id, b.contact_email, b.contact_name,
       b.status, b.total_amount_minor, b.currency,
       b.payment_method, b.paid_at, b.created_at,
       COUNT(p.id)::int AS participant_count,
       COALESCE(string_agg(p.name, '|' ORDER BY p.created_at), '')::text AS participant_names
FROM bookings b
LEFT JOIN participants p ON p.booking_id = b.id
WHERE b.event_id = $1
  AND ($2::text IS NULL OR b.status = $2::text)
  AND ($3::text IS NULL OR b.payment_method = $3::text)
  AND ($4::timestamptz IS NULL OR b.created_at >= $4::timestamptz)
  AND ($5::timestamptz   IS NULL OR b.created_at <  $5::timestamptz)
  AND ($6::text IS NULL OR
       lower(b.contact_email) LIKE '%' || lower($6::text) || '%' OR
       lower(b.contact_name)  LIKE '%' || lower($6::text) || '%' OR
       upper(substring(replace(b.id::text, '-', '') from 1 for 8)) LIKE upper('%' || $6::text || '%'))
GROUP BY b.id
ORDER BY b.created_at ASC
`

type ListExpandedBookingsForEventParams struct {
	EventID       uuid.UUID
	Status        *string
	PaymentMethod *string
	FromTs        *time.Time
	ToTs          *time.Time
	Q             *string
}

type ListExpandedBookingsForEventRow struct {
	ID               uuid.UUID
	ContactEmail     string
	ContactName      string
	Status           string
	TotalAmountMinor int64
	Currency         string
	PaymentMethod    *string
	PaidAt           *time.Time
	CreatedAt        time.Time
	ParticipantCount int32
	ParticipantNames string
}

// CSV export. Same filter contract as SearchBookingsForEvent but without
// pagination — caller streams. Participant names are aggregated into a
// pipe-separated string so each row stays atomic in the CSV.
func (q *Queries) ListExpandedBookingsForEvent(ctx context.Context, arg ListExpandedBookingsForEventParams) ([]ListExpandedBookingsForEventRow, error) {
	rows, err := q.db.Query(ctx, listExpandedBookingsForEvent,
		arg.EventID,
		arg.Status,
		arg.PaymentMethod,
		arg.FromTs,
		arg.ToTs,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpandedBookingsForEventRow{}
	for rows.Next() {
		var i ListExpandedBookingsForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.ContactEmail,
			&i.ContactName,
			&i.Status,
			&i.TotalAmountMinor,
			&i.Currency,
			&i.PaymentMethod,
			&i.PaidAt,
			&i.CreatedAt,
			&i.ParticipantCount,
			&i.ParticipantNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredUnpaidBookings = `-- name: ListExpiredUnpaidBookings :many
SELECT id, event_id FROM bookings
WHERE status = 'booked'
  AND reservation_expires_at IS NOT NULL
  AND reservation_expires_at < now()
`

type ListExpiredUnpaidBookingsRow struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

// Returns booking ids that have status='booked' and reservation_expires_at
// in the past. Sweeper invokes this and then cascades to ticket cancel.
func (q *Queries) ListExpiredUnpaidBookings(ctx context.Context) ([]ListExpiredUnpaidBookingsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredUnpaidBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredUnpaidBookingsRow{}
	for rows.Next() {
		var i ListExpiredUnpaidBookingsRow
		if err := rows.Scan(&i.ID, &i.EventID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsForBooking = `-- name: ListParticipantsForBooking :many
SELECT id, event_id, booking_id, name, email, newsletter_optin, notes, created_at FROM participants WHERE booking_id = $1 ORDER BY created_at
`

func (q *Queries) ListParticipantsForBooking(ctx context.Context, bookingID uuid.UUID) ([]Participant, error) {
	rows, err := q.db.Query(ctx, listParticipantsForBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.BookingID,
			&i.Name,
			&i.Email,
			&i.NewsletterOptin,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBookingPaid = `-- name: MarkBookingPaid :exec
UPDATE bookings
SET status = 'paid',
    paid_at = now(),
    payment_method = COALESCE(payment_method, $2)
WHERE id = $1 AND status = 'booked'
`

type MarkBookingPaidParams struct {
	ID            uuid.UUID
	PaymentMethod *string
}

func (q *Queries) MarkBookingPaid(ctx context.Context, arg MarkBookingPaidParams) error {
	_, err := q.db.Exec(ctx, markBookingPaid, arg.ID, arg.PaymentMethod)
	return err
}

const markBookingTicketsPaid = `-- name: MarkBookingTicketsPaid :exec
UPDATE tickets
SET status = 'paid', paid_at = now()
WHERE booking_id = $1 AND status = 'booked'
`

func (q *Queries) MarkBookingTicketsPaid(ctx context.Context, bookingID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBookingTicketsPaid, bookingID)
	return err
}

const purgeTestBookingsForEvent = `-- name: PurgeTestBookingsForEvent :execrows
DELETE FROM bookings WHERE event_id = $1 AND payment_method = 'test'
`

// Deletes all bookings on an event that were created in test mode
// (payment_method='test'). Cascade deletes participants + tickets + redemptions.
func (q *Queries) PurgeTestBookingsForEvent(ctx context.Context, eventID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeTestBookingsForEvent, eventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchBookingsForEvent = `-- name: SearchBookingsForEvent :many
SELECT b.id, b.event_id, b.contact_email, b.contact_name, b.contact_phone,
       b.locale, b.status, b.total_amount_minor, b.currency, b.coupon_id,
       b.payment_method, b.payment_reference, b.reservation_expires_at,
       b.created_at, b.paid_at, b.canceled_at,
       COUNT(p.id)::int AS participant_count
FROM bookings b
LEFT JOIN participants p ON p.booking_id = b.id
WHERE b.event_id = $1
  AND ($2::text IS NULL OR b.status = $2::text)
  AND ($3::text IS NULL OR b.payment_method = $3::text)
  AND ($4::timestamptz IS NULL OR b.created_at >= $4::timestamptz)
  AND ($5::timestamptz   IS NULL OR b.created_at <  $5::timestamptz)
  AND ($6::text IS NULL OR
       lower(b.contact_email) LIKE '%' || lower($6::text) || '%' OR
       lower(b.contact_name)  LIKE '%' || lower($6::text) || '%' OR
       upper(substring(replace(b.id::text, '-', '') from 1 for 8)) LIKE upper('%' || $6::text || '%'))
GROUP BY b.id
ORDER BY
    CASE WHEN $7::text = 'paid_at_desc'      THEN b.paid_at      END DESC NULLS LAST,
    CASE WHEN $7::text = 'paid_at_asc'       THEN b.paid_at      END ASC  NULLS LAST,
    CASE WHEN $7::text = 'total_desc'        THEN b.total_amount_minor END DESC,
    CASE WHEN $7::text = 'total_asc'         THEN b.total_amount_minor END ASC,
    CASE WHEN $7::text = 'name_asc'          THEN lower(b.contact_name) END ASC,
    CASE WHEN $7::text = 'created_at_asc'    THEN b.created_at END ASC,
    b.created_at DESC
LIMIT $9::int OFFSET $8::int
`

type SearchBookingsForEventParams struct {
	EventID       uuid.UUID
	Status        *string
	PaymentMethod *string
	FromTs        *time.Time
	ToTs          *time.Time
	Q             *string
	Sort          string
	OffsetN       int32
	LimitN        int32
}

type SearchBookingsForEventRow struct {
	ID                   uuid.UUID
	EventID              uuid.UUID
	ContactEmail         string
	ContactName          string
	ContactPhone         *string
	Locale               string
	Status               string
	TotalAmountMinor     int64
	Currency             string
	CouponID             *uuid.UUID
	PaymentMethod        *string
	PaymentReference     *string
	ReservationExpiresAt *time.Time
	CreatedAt            time.Time
	PaidAt               *time.Time
	CanceledAt           *time.Time
	ParticipantCount     int32
}

// Paginated + filterable admin list. Empty filter args are NULL — the WHERE
// clauses treat NULL as "no filter on this column". Reference search uses the
// first 8 hex chars of the booking UUID (matches formatReference() output).
// Search across email + name uses trigram-indexed lower() ILIKE.
func (q *Queries) SearchBookingsForEvent(ctx context.Context, arg SearchBookingsForEventParams) ([]SearchBookingsForEventRow, error) {
	rows, err := q.db.Query(ctx, searchBookingsForEvent,
		arg.EventID,
		arg.Status,
		arg.PaymentMethod,
		arg.FromTs,
		arg.ToTs,
		arg.Q,
		arg.Sort,
		arg.OffsetN,
		arg.LimitN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchBookingsForEventRow{}
	for rows.Next() {
		var i SearchBookingsForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ContactEmail,
			&i.ContactName,
			&i.ContactPhone,
			&i.Locale,
			&i.Status,
			&i.TotalAmountMinor,
			&i.Currency,
			&i.CouponID,
			&i.PaymentMethod,
			&i.PaymentReference,
			&i.ReservationExpiresAt,
			&i.CreatedAt,
			&i.PaidAt,
			&i.CanceledAt,
			&i.ParticipantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingContactEmail = `-- name: UpdateBookingContactEmail :exec
UPDATE bookings SET contact_email = $2 WHERE id = $1
`

type UpdateBookingContactEmailParams struct {
	ID           uuid.UUID
	ContactEmail string
}

// Narrow PATCH endpoint for typo fixes. Returns no rows; the handler re-loads
// if it needs to echo the updated state back. Audit-log the old/new values
// at the handler level (the row update is the source of truth for the new
// value).
func (q *Queries) UpdateBookingContactEmail(ctx context.Context, arg UpdateBookingContactEmailParams) error {
	_, err := q.db.Exec(ctx, updateBookingContactEmail, arg.ID, arg.ContactEmail)
	return err
}
