// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_log.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertEmailLog = `-- name: InsertEmailLog :exec
INSERT INTO email_log (
    to_email, template, subject, locale, status, error, ses_message_id,
    related_event_id, related_booking_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertEmailLogParams struct {
	ToEmail          string
	Template         string
	Subject          string
	Locale           string
	Status           string
	Error            *string
	SesMessageID     *string
	RelatedEventID   *uuid.UUID
	RelatedBookingID *uuid.UUID
}

func (q *Queries) InsertEmailLog(ctx context.Context, arg InsertEmailLogParams) error {
	_, err := q.db.Exec(ctx, insertEmailLog,
		arg.ToEmail,
		arg.Template,
		arg.Subject,
		arg.Locale,
		arg.Status,
		arg.Error,
		arg.SesMessageID,
		arg.RelatedEventID,
		arg.RelatedBookingID,
	)
	return err
}
