// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_team.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignEventAdmin = `-- name: AssignEventAdmin :exec
INSERT INTO event_admins (user_id, event_id)
VALUES ($1, $2)
ON CONFLICT (user_id, event_id) DO NOTHING
`

type AssignEventAdminParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) AssignEventAdmin(ctx context.Context, arg AssignEventAdminParams) error {
	_, err := q.db.Exec(ctx, assignEventAdmin, arg.UserID, arg.EventID)
	return err
}

const assignEventManager = `-- name: AssignEventManager :exec
INSERT INTO event_managers (user_id, event_id)
VALUES ($1, $2)
ON CONFLICT (user_id, event_id) DO NOTHING
`

type AssignEventManagerParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) AssignEventManager(ctx context.Context, arg AssignEventManagerParams) error {
	_, err := q.db.Exec(ctx, assignEventManager, arg.UserID, arg.EventID)
	return err
}

const listEventAdminUsers = `-- name: ListEventAdminUsers :many
SELECT u.id, u.email, u.role, u.display_name, u.disabled_at, ea.assigned_at
FROM event_admins ea
JOIN users u ON u.id = ea.user_id
WHERE ea.event_id = $1
ORDER BY ea.assigned_at
`

type ListEventAdminUsersRow struct {
	ID          uuid.UUID
	Email       string
	Role        string
	DisplayName *string
	DisabledAt  *time.Time
	AssignedAt  time.Time
}

func (q *Queries) ListEventAdminUsers(ctx context.Context, eventID uuid.UUID) ([]ListEventAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listEventAdminUsers, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventAdminUsersRow{}
	for rows.Next() {
		var i ListEventAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.DisplayName,
			&i.DisabledAt,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventManagerUsers = `-- name: ListEventManagerUsers :many
SELECT u.id, u.email, u.role, u.display_name, u.disabled_at, em.assigned_at
FROM event_managers em
JOIN users u ON u.id = em.user_id
WHERE em.event_id = $1
ORDER BY em.assigned_at
`

type ListEventManagerUsersRow struct {
	ID          uuid.UUID
	Email       string
	Role        string
	DisplayName *string
	DisabledAt  *time.Time
	AssignedAt  time.Time
}

func (q *Queries) ListEventManagerUsers(ctx context.Context, eventID uuid.UUID) ([]ListEventManagerUsersRow, error) {
	rows, err := q.db.Query(ctx, listEventManagerUsers, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventManagerUsersRow{}
	for rows.Next() {
		var i ListEventManagerUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.DisplayName,
			&i.DisabledAt,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignEventAdmin = `-- name: UnassignEventAdmin :exec
DELETE FROM event_admins WHERE user_id = $1 AND event_id = $2
`

type UnassignEventAdminParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) UnassignEventAdmin(ctx context.Context, arg UnassignEventAdminParams) error {
	_, err := q.db.Exec(ctx, unassignEventAdmin, arg.UserID, arg.EventID)
	return err
}

const unassignEventManager = `-- name: UnassignEventManager :exec
DELETE FROM event_managers WHERE user_id = $1 AND event_id = $2
`

type UnassignEventManagerParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) UnassignEventManager(ctx context.Context, arg UnassignEventManagerParams) error {
	_, err := q.db.Exec(ctx, unassignEventManager, arg.UserID, arg.EventID)
	return err
}
