// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveEvent = `-- name: ArchiveEvent :exec
UPDATE events SET archived_at = now() WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveEvent, id)
	return err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    slug, name, description, banner_ref,
    color_primary, color_secondary, color_text,
    location, starts_at, ends_at, participant_limit,
    pricing_mode, currency, default_locale,
    is_public, created_by,
    payment_timing, bank_iban, bank_bic, bank_account_holder,
    paypal_handle, payment_test_mode
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16,
    $17, $18, $19, $20,
    $21, $22
)
RETURNING id, slug, name, description, banner_ref, color_primary, color_secondary, color_text, location, starts_at, ends_at, participant_limit, pricing_mode, currency, default_locale, is_public, archived_at, created_by, created_at, payment_timing, bank_iban, bank_bic, bank_account_holder, paypal_handle, payment_test_mode, waitlist_claim_window_hours
`

type CreateEventParams struct {
	Slug              string
	Name              string
	Description       string
	BannerRef         *string
	ColorPrimary      string
	ColorSecondary    string
	ColorText         string
	Location          string
	StartsAt          time.Time
	EndsAt            time.Time
	ParticipantLimit  *int32
	PricingMode       string
	Currency          string
	DefaultLocale     string
	IsPublic          bool
	CreatedBy         uuid.UUID
	PaymentTiming     string
	BankIban          *string
	BankBic           *string
	BankAccountHolder *string
	PaypalHandle      *string
	PaymentTestMode   bool
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.BannerRef,
		arg.ColorPrimary,
		arg.ColorSecondary,
		arg.ColorText,
		arg.Location,
		arg.StartsAt,
		arg.EndsAt,
		arg.ParticipantLimit,
		arg.PricingMode,
		arg.Currency,
		arg.DefaultLocale,
		arg.IsPublic,
		arg.CreatedBy,
		arg.PaymentTiming,
		arg.BankIban,
		arg.BankBic,
		arg.BankAccountHolder,
		arg.PaypalHandle,
		arg.PaymentTestMode,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.BannerRef,
		&i.ColorPrimary,
		&i.ColorSecondary,
		&i.ColorText,
		&i.Location,
		&i.StartsAt,
		&i.EndsAt,
		&i.ParticipantLimit,
		&i.PricingMode,
		&i.Currency,
		&i.DefaultLocale,
		&i.IsPublic,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PaymentTiming,
		&i.BankIban,
		&i.BankBic,
		&i.BankAccountHolder,
		&i.PaypalHandle,
		&i.PaymentTestMode,
		&i.WaitlistClaimWindowHours,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, slug, name, description, banner_ref, color_primary, color_secondary, color_text, location, starts_at, ends_at, participant_limit, pricing_mode, currency, default_locale, is_public, archived_at, created_by, created_at, payment_timing, bank_iban, bank_bic, bank_account_holder, paypal_handle, payment_test_mode, waitlist_claim_window_hours FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.BannerRef,
		&i.ColorPrimary,
		&i.ColorSecondary,
		&i.ColorText,
		&i.Location,
		&i.StartsAt,
		&i.EndsAt,
		&i.ParticipantLimit,
		&i.PricingMode,
		&i.Currency,
		&i.DefaultLocale,
		&i.IsPublic,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PaymentTiming,
		&i.BankIban,
		&i.BankBic,
		&i.BankAccountHolder,
		&i.PaypalHandle,
		&i.PaymentTestMode,
		&i.WaitlistClaimWindowHours,
	)
	return i, err
}

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT id, slug, name, description, banner_ref, color_primary, color_secondary, color_text, location, starts_at, ends_at, participant_limit, pricing_mode, currency, default_locale, is_public, archived_at, created_by, created_at, payment_timing, bank_iban, bank_bic, bank_account_holder, paypal_handle, payment_test_mode, waitlist_claim_window_hours FROM events WHERE slug = $1
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.BannerRef,
		&i.ColorPrimary,
		&i.ColorSecondary,
		&i.ColorText,
		&i.Location,
		&i.StartsAt,
		&i.EndsAt,
		&i.ParticipantLimit,
		&i.PricingMode,
		&i.Currency,
		&i.DefaultLocale,
		&i.IsPublic,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PaymentTiming,
		&i.BankIban,
		&i.BankBic,
		&i.BankAccountHolder,
		&i.PaypalHandle,
		&i.PaymentTestMode,
		&i.WaitlistClaimWindowHours,
	)
	return i, err
}

const isEventAdmin = `-- name: IsEventAdmin :one
SELECT EXISTS (
    SELECT 1 FROM event_admins
    WHERE event_id = $1 AND user_id = $2
)
`

type IsEventAdminParams struct {
	EventID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) IsEventAdmin(ctx context.Context, arg IsEventAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEventAdmin, arg.EventID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isEventManager = `-- name: IsEventManager :one
SELECT EXISTS (
    SELECT 1 FROM event_managers
    WHERE event_id = $1 AND user_id = $2
)
`

type IsEventManagerParams struct {
	EventID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) IsEventManager(ctx context.Context, arg IsEventManagerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEventManager, arg.EventID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEventsForGlobalAdmin = `-- name: ListEventsForGlobalAdmin :many
SELECT id, slug, name, description, banner_ref, color_primary, color_secondary, color_text, location, starts_at, ends_at, participant_limit, pricing_mode, currency, default_locale, is_public, archived_at, created_by, created_at, payment_timing, bank_iban, bank_bic, bank_account_holder, paypal_handle, payment_test_mode, waitlist_claim_window_hours FROM events
ORDER BY starts_at DESC
`

func (q *Queries) ListEventsForGlobalAdmin(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsForGlobalAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.BannerRef,
			&i.ColorPrimary,
			&i.ColorSecondary,
			&i.ColorText,
			&i.Location,
			&i.StartsAt,
			&i.EndsAt,
			&i.ParticipantLimit,
			&i.PricingMode,
			&i.Currency,
			&i.DefaultLocale,
			&i.IsPublic,
			&i.ArchivedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PaymentTiming,
			&i.BankIban,
			&i.BankBic,
			&i.BankAccountHolder,
			&i.PaypalHandle,
			&i.PaymentTestMode,
			&i.WaitlistClaimWindowHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForUser = `-- name: ListEventsForUser :many
SELECT DISTINCT e.id, e.slug, e.name, e.description, e.banner_ref, e.color_primary, e.color_secondary, e.color_text, e.location, e.starts_at, e.ends_at, e.participant_limit, e.pricing_mode, e.currency, e.default_locale, e.is_public, e.archived_at, e.created_by, e.created_at, e.payment_timing, e.bank_iban, e.bank_bic, e.bank_account_holder, e.paypal_handle, e.payment_test_mode, e.waitlist_claim_window_hours FROM events e
LEFT JOIN event_admins ea ON ea.event_id = e.id AND ea.user_id = $1
LEFT JOIN event_managers em ON em.event_id = e.id AND em.user_id = $1
WHERE ea.user_id IS NOT NULL OR em.user_id IS NOT NULL
ORDER BY e.starts_at DESC
`

// Events the user can see as event_admin OR event_manager.
func (q *Queries) ListEventsForUser(ctx context.Context, userID uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.BannerRef,
			&i.ColorPrimary,
			&i.ColorSecondary,
			&i.ColorText,
			&i.Location,
			&i.StartsAt,
			&i.EndsAt,
			&i.ParticipantLimit,
			&i.PricingMode,
			&i.Currency,
			&i.DefaultLocale,
			&i.IsPublic,
			&i.ArchivedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PaymentTiming,
			&i.BankIban,
			&i.BankBic,
			&i.BankAccountHolder,
			&i.PaypalHandle,
			&i.PaymentTestMode,
			&i.WaitlistClaimWindowHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicUpcomingEvents = `-- name: ListPublicUpcomingEvents :many
SELECT id, slug, name, description, banner_ref, color_primary, color_secondary, color_text, location, starts_at, ends_at, participant_limit, pricing_mode, currency, default_locale, is_public, archived_at, created_by, created_at, payment_timing, bank_iban, bank_bic, bank_account_holder, paypal_handle, payment_test_mode, waitlist_claim_window_hours FROM events
WHERE is_public = TRUE
  AND archived_at IS NULL
  AND ends_at > now()
ORDER BY starts_at ASC
`

func (q *Queries) ListPublicUpcomingEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listPublicUpcomingEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.BannerRef,
			&i.ColorPrimary,
			&i.ColorSecondary,
			&i.ColorText,
			&i.Location,
			&i.StartsAt,
			&i.EndsAt,
			&i.ParticipantLimit,
			&i.PricingMode,
			&i.Currency,
			&i.DefaultLocale,
			&i.IsPublic,
			&i.ArchivedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PaymentTiming,
			&i.BankIban,
			&i.BankBic,
			&i.BankAccountHolder,
			&i.PaypalHandle,
			&i.PaymentTestMode,
			&i.WaitlistClaimWindowHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishEvent = `-- name: PublishEvent :exec
UPDATE events SET is_public = TRUE WHERE id = $1
`

func (q *Queries) PublishEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, publishEvent, id)
	return err
}

const setEventBanner = `-- name: SetEventBanner :exec
UPDATE events SET banner_ref = $2 WHERE id = $1
`

type SetEventBannerParams struct {
	ID        uuid.UUID
	BannerRef *string
}

func (q *Queries) SetEventBanner(ctx context.Context, arg SetEventBannerParams) error {
	_, err := q.db.Exec(ctx, setEventBanner, arg.ID, arg.BannerRef)
	return err
}

const slugTaken = `-- name: SlugTaken :one
SELECT EXISTS (SELECT 1 FROM events WHERE slug = $1)
`

func (q *Queries) SlugTaken(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugTaken, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unarchiveEvent = `-- name: UnarchiveEvent :exec
UPDATE events SET archived_at = NULL WHERE id = $1
`

func (q *Queries) UnarchiveEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unarchiveEvent, id)
	return err
}

const unpublishEvent = `-- name: UnpublishEvent :exec
UPDATE events SET is_public = FALSE WHERE id = $1
`

func (q *Queries) UnpublishEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unpublishEvent, id)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    name = $2,
    description = $3,
    color_primary = $4,
    color_secondary = $5,
    color_text = $6,
    location = $7,
    starts_at = $8,
    ends_at = $9,
    participant_limit = $10,
    pricing_mode = $11,
    currency = $12,
    default_locale = $13,
    payment_timing = $14,
    bank_iban = $15,
    bank_bic = $16,
    bank_account_holder = $17,
    paypal_handle = $18,
    payment_test_mode = $19
WHERE id = $1
RETURNING id, slug, name, description, banner_ref, color_primary, color_secondary, color_text, location, starts_at, ends_at, participant_limit, pricing_mode, currency, default_locale, is_public, archived_at, created_by, created_at, payment_timing, bank_iban, bank_bic, bank_account_holder, paypal_handle, payment_test_mode, waitlist_claim_window_hours
`

type UpdateEventParams struct {
	ID                uuid.UUID
	Name              string
	Description       string
	ColorPrimary      string
	ColorSecondary    string
	ColorText         string
	Location          string
	StartsAt          time.Time
	EndsAt            time.Time
	ParticipantLimit  *int32
	PricingMode       string
	Currency          string
	DefaultLocale     string
	PaymentTiming     string
	BankIban          *string
	BankBic           *string
	BankAccountHolder *string
	PaypalHandle      *string
	PaymentTestMode   bool
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ColorPrimary,
		arg.ColorSecondary,
		arg.ColorText,
		arg.Location,
		arg.StartsAt,
		arg.EndsAt,
		arg.ParticipantLimit,
		arg.PricingMode,
		arg.Currency,
		arg.DefaultLocale,
		arg.PaymentTiming,
		arg.BankIban,
		arg.BankBic,
		arg.BankAccountHolder,
		arg.PaypalHandle,
		arg.PaymentTestMode,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.BannerRef,
		&i.ColorPrimary,
		&i.ColorSecondary,
		&i.ColorText,
		&i.Location,
		&i.StartsAt,
		&i.EndsAt,
		&i.ParticipantLimit,
		&i.PricingMode,
		&i.Currency,
		&i.DefaultLocale,
		&i.IsPublic,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PaymentTiming,
		&i.BankIban,
		&i.BankBic,
		&i.BankAccountHolder,
		&i.PaypalHandle,
		&i.PaymentTestMode,
		&i.WaitlistClaimWindowHours,
	)
	return i, err
}
