// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID          uuid.UUID
	ActorUserID *uuid.UUID
	EventID     *uuid.UUID
	Action      string
	TargetKind  string
	TargetID    *string
	Payload     []byte
	CreatedAt   time.Time
}

type Booking struct {
	ID                   uuid.UUID
	EventID              uuid.UUID
	ContactEmail         string
	ContactName          string
	ContactPhone         *string
	Locale               string
	Status               string
	TotalAmountMinor     int64
	Currency             string
	CouponID             *uuid.UUID
	PaymentMethod        *string
	PaymentReference     *string
	ReservationExpiresAt *time.Time
	CreatedAt            time.Time
	PaidAt               *time.Time
	CanceledAt           *time.Time
}

type Coupon struct {
	ID                uuid.UUID
	EventID           uuid.UUID
	Code              string
	Type              string
	ValueMinor        *int64
	ValuePercent      *int32
	MaxUses           *int32
	ValidFrom         *time.Time
	ValidTo           *time.Time
	SingleUsePerEmail bool
	CreatedAt         time.Time
}

type CouponCategoryFilter struct {
	CouponID   uuid.UUID
	CategoryID uuid.UUID
}

type CouponPhaseFilter struct {
	CouponID uuid.UUID
	PhaseID  uuid.UUID
}

type CouponRedemption struct {
	ID         uuid.UUID
	CouponID   uuid.UUID
	BookingID  uuid.UUID
	RedeemedAt time.Time
}

type DonationConfig struct {
	EventID        uuid.UUID
	SuggestedMinor int64
	MinMinor       int64
}

type EmailLog struct {
	ID               uuid.UUID
	ToEmail          string
	Template         string
	Subject          string
	Locale           string
	Status           string
	Error            *string
	SesMessageID     *string
	RelatedEventID   *uuid.UUID
	RelatedBookingID *uuid.UUID
	SentAt           time.Time
}

type Event struct {
	ID                       uuid.UUID
	Slug                     string
	Name                     string
	Description              string
	BannerRef                *string
	ColorPrimary             string
	ColorSecondary           string
	ColorText                string
	Location                 string
	StartsAt                 time.Time
	EndsAt                   time.Time
	ParticipantLimit         *int32
	PricingMode              string
	Currency                 string
	DefaultLocale            string
	IsPublic                 bool
	ArchivedAt               *time.Time
	CreatedBy                uuid.UUID
	CreatedAt                time.Time
	PaymentTiming            string
	BankIban                 *string
	BankBic                  *string
	BankAccountHolder        *string
	PaypalHandle             *string
	PaymentTestMode          bool
	WaitlistClaimWindowHours int32
}

type EventAdmin struct {
	UserID     uuid.UUID
	EventID    uuid.UUID
	AssignedAt time.Time
}

type EventManager struct {
	UserID     uuid.UUID
	EventID    uuid.UUID
	AssignedAt time.Time
}

type Participant struct {
	ID              uuid.UUID
	EventID         uuid.UUID
	BookingID       uuid.UUID
	Name            string
	Email           *string
	NewsletterOptin bool
	Notes           *string
	CreatedAt       time.Time
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Price struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	PhaseID     uuid.UUID
	CategoryID  uuid.UUID
	DurationID  *uuid.UUID
	AmountMinor int64
}

type PriceCategory struct {
	ID       uuid.UUID
	EventID  uuid.UUID
	Name     string
	Ordering int32
}

type PriceDuration struct {
	ID       uuid.UUID
	EventID  uuid.UUID
	Name     string
	Ordering int32
}

type PricePhase struct {
	ID       uuid.UUID
	EventID  uuid.UUID
	Name     string
	StartsAt time.Time
	EndsAt   time.Time
	Ordering int32
}

type ProgramEntry struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	StartsAt    time.Time
	EndsAt      *time.Time
	Title       string
	Description string
	Ordering    int32
}

type Session struct {
	ID                 []byte
	UserID             uuid.UUID
	CreatedAt          time.Time
	LastSeenAt         time.Time
	ExpiresAt          time.Time
	RevokedAt          *time.Time
	UserAgent          *string
	Ip                 *netip.Addr
	PasswordVersion    int32
	ImpersonatorUserID *uuid.UUID
}

type SetupToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Ticket struct {
	ID              uuid.UUID
	BookingID       uuid.UUID
	ParticipantID   uuid.UUID
	EventID         uuid.UUID
	Status          string
	QrToken         string
	PhaseID         *uuid.UUID
	CategoryID      *uuid.UUID
	DurationID      *uuid.UUID
	AmountMinor     int64
	CreatedAt       time.Time
	PaidAt          *time.Time
	CanceledAt      *time.Time
	CheckedInAt     *time.Time
	QrNonce         []byte
	PaidAmountMinor *int64
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	Role            string
	DisplayName     *string
	CreatedAt       time.Time
	DisabledAt      *time.Time
	PasswordVersion int32
	Active          bool
	LastLoginAt     *time.Time
}

type WaitlistEntry struct {
	ID                 uuid.UUID
	EventID            uuid.UUID
	ContactEmail       string
	ContactName        string
	Locale             string
	RequestedSeats     int32
	SelectionJson      []byte
	CreatedAt          time.Time
	PromotedAt         *time.Time
	ClaimDeadline      *time.Time
	FulfilledBookingID *uuid.UUID
	Status             string
	CouponID           *uuid.UUID
}
