// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pricing.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCouponCategoryFilter = `-- name: AddCouponCategoryFilter :exec
INSERT INTO coupon_category_filters (coupon_id, category_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddCouponCategoryFilterParams struct {
	CouponID   uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) AddCouponCategoryFilter(ctx context.Context, arg AddCouponCategoryFilterParams) error {
	_, err := q.db.Exec(ctx, addCouponCategoryFilter, arg.CouponID, arg.CategoryID)
	return err
}

const addCouponPhaseFilter = `-- name: AddCouponPhaseFilter :exec
INSERT INTO coupon_phase_filters (coupon_id, phase_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddCouponPhaseFilterParams struct {
	CouponID uuid.UUID
	PhaseID  uuid.UUID
}

func (q *Queries) AddCouponPhaseFilter(ctx context.Context, arg AddCouponPhaseFilterParams) error {
	_, err := q.db.Exec(ctx, addCouponPhaseFilter, arg.CouponID, arg.PhaseID)
	return err
}

const clearCouponCategoryFilters = `-- name: ClearCouponCategoryFilters :exec
DELETE FROM coupon_category_filters WHERE coupon_id = $1
`

func (q *Queries) ClearCouponCategoryFilters(ctx context.Context, couponID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCouponCategoryFilters, couponID)
	return err
}

const clearCouponPhaseFilters = `-- name: ClearCouponPhaseFilters :exec
DELETE FROM coupon_phase_filters WHERE coupon_id = $1
`

func (q *Queries) ClearCouponPhaseFilters(ctx context.Context, couponID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCouponPhaseFilters, couponID)
	return err
}

const countCouponRedemptions = `-- name: CountCouponRedemptions :one
SELECT count(*)::int AS uses FROM coupon_redemptions WHERE coupon_id = $1
`

func (q *Queries) CountCouponRedemptions(ctx context.Context, couponID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCouponRedemptions, couponID)
	var uses int32
	err := row.Scan(&uses)
	return uses, err
}

const countCouponRedemptionsForEmail = `-- name: CountCouponRedemptionsForEmail :one
SELECT count(*)::int AS uses
FROM coupon_redemptions cr
JOIN bookings b ON b.id = cr.booking_id
WHERE cr.coupon_id = $1 AND lower(b.contact_email) = lower($2)
`

type CountCouponRedemptionsForEmailParams struct {
	CouponID uuid.UUID
	Lower    string
}

// Counts how many bookings using contact_email have redeemed this coupon
// (used for single_use_per_email enforcement).
func (q *Queries) CountCouponRedemptionsForEmail(ctx context.Context, arg CountCouponRedemptionsForEmailParams) (int32, error) {
	row := q.db.QueryRow(ctx, countCouponRedemptionsForEmail, arg.CouponID, arg.Lower)
	var uses int32
	err := row.Scan(&uses)
	return uses, err
}

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (
    event_id, code, type, value_minor, value_percent,
    max_uses, valid_from, valid_to, single_use_per_email
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, event_id, code, type, value_minor, value_percent, max_uses, valid_from, valid_to, single_use_per_email, created_at
`

type CreateCouponParams struct {
	EventID           uuid.UUID
	Code              string
	Type              string
	ValueMinor        *int64
	ValuePercent      *int32
	MaxUses           *int32
	ValidFrom         *time.Time
	ValidTo           *time.Time
	SingleUsePerEmail bool
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.EventID,
		arg.Code,
		arg.Type,
		arg.ValueMinor,
		arg.ValuePercent,
		arg.MaxUses,
		arg.ValidFrom,
		arg.ValidTo,
		arg.SingleUsePerEmail,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Code,
		&i.Type,
		&i.ValueMinor,
		&i.ValuePercent,
		&i.MaxUses,
		&i.ValidFrom,
		&i.ValidTo,
		&i.SingleUsePerEmail,
		&i.CreatedAt,
	)
	return i, err
}

const createPriceCategory = `-- name: CreatePriceCategory :one
INSERT INTO price_categories (event_id, name, ordering)
VALUES ($1, $2, $3)
RETURNING id, event_id, name, ordering
`

type CreatePriceCategoryParams struct {
	EventID  uuid.UUID
	Name     string
	Ordering int32
}

func (q *Queries) CreatePriceCategory(ctx context.Context, arg CreatePriceCategoryParams) (PriceCategory, error) {
	row := q.db.QueryRow(ctx, createPriceCategory, arg.EventID, arg.Name, arg.Ordering)
	var i PriceCategory
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Ordering,
	)
	return i, err
}

const createPriceDuration = `-- name: CreatePriceDuration :one
INSERT INTO price_durations (event_id, name, ordering)
VALUES ($1, $2, $3)
RETURNING id, event_id, name, ordering
`

type CreatePriceDurationParams struct {
	EventID  uuid.UUID
	Name     string
	Ordering int32
}

func (q *Queries) CreatePriceDuration(ctx context.Context, arg CreatePriceDurationParams) (PriceDuration, error) {
	row := q.db.QueryRow(ctx, createPriceDuration, arg.EventID, arg.Name, arg.Ordering)
	var i PriceDuration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Ordering,
	)
	return i, err
}

const createPricePhase = `-- name: CreatePricePhase :one
INSERT INTO price_phases (event_id, name, starts_at, ends_at, ordering)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, event_id, name, starts_at, ends_at, ordering
`

type CreatePricePhaseParams struct {
	EventID  uuid.UUID
	Name     string
	StartsAt time.Time
	EndsAt   time.Time
	Ordering int32
}

func (q *Queries) CreatePricePhase(ctx context.Context, arg CreatePricePhaseParams) (PricePhase, error) {
	row := q.db.QueryRow(ctx, createPricePhase,
		arg.EventID,
		arg.Name,
		arg.StartsAt,
		arg.EndsAt,
		arg.Ordering,
	)
	var i PricePhase
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.Ordering,
	)
	return i, err
}

const deleteCoupon = `-- name: DeleteCoupon :exec
DELETE FROM coupons WHERE id = $1
`

func (q *Queries) DeleteCoupon(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoupon, id)
	return err
}

const deleteDonationConfig = `-- name: DeleteDonationConfig :exec
DELETE FROM donation_configs WHERE event_id = $1
`

func (q *Queries) DeleteDonationConfig(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDonationConfig, eventID)
	return err
}

const deletePrice = `-- name: DeletePrice :exec
DELETE FROM prices WHERE id = $1
`

func (q *Queries) DeletePrice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePrice, id)
	return err
}

const deletePriceCategory = `-- name: DeletePriceCategory :exec
DELETE FROM price_categories WHERE id = $1
`

func (q *Queries) DeletePriceCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePriceCategory, id)
	return err
}

const deletePriceDuration = `-- name: DeletePriceDuration :exec
DELETE FROM price_durations WHERE id = $1
`

func (q *Queries) DeletePriceDuration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePriceDuration, id)
	return err
}

const deletePricePhase = `-- name: DeletePricePhase :exec
DELETE FROM price_phases WHERE id = $1
`

func (q *Queries) DeletePricePhase(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePricePhase, id)
	return err
}

const getActivePhaseForEvent = `-- name: GetActivePhaseForEvent :one
SELECT id, event_id, name, starts_at, ends_at, ordering FROM price_phases
WHERE event_id = $1
  AND starts_at <= $2 AND ends_at > $2
ORDER BY ordering, id
LIMIT 1
`

type GetActivePhaseForEventParams struct {
	EventID  uuid.UUID
	StartsAt time.Time
}

// Returns the phase whose [starts_at, ends_at) contains $2.
// If multiple phases overlap, the lowest `ordering` wins; ties broken by id.
func (q *Queries) GetActivePhaseForEvent(ctx context.Context, arg GetActivePhaseForEventParams) (PricePhase, error) {
	row := q.db.QueryRow(ctx, getActivePhaseForEvent, arg.EventID, arg.StartsAt)
	var i PricePhase
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.Ordering,
	)
	return i, err
}

const getCoupon = `-- name: GetCoupon :one
SELECT id, event_id, code, type, value_minor, value_percent, max_uses, valid_from, valid_to, single_use_per_email, created_at FROM coupons WHERE id = $1
`

func (q *Queries) GetCoupon(ctx context.Context, id uuid.UUID) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCoupon, id)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Code,
		&i.Type,
		&i.ValueMinor,
		&i.ValuePercent,
		&i.MaxUses,
		&i.ValidFrom,
		&i.ValidTo,
		&i.SingleUsePerEmail,
		&i.CreatedAt,
	)
	return i, err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, event_id, code, type, value_minor, value_percent, max_uses, valid_from, valid_to, single_use_per_email, created_at FROM coupons WHERE event_id = $1 AND code = $2
`

type GetCouponByCodeParams struct {
	EventID uuid.UUID
	Code    string
}

func (q *Queries) GetCouponByCode(ctx context.Context, arg GetCouponByCodeParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByCode, arg.EventID, arg.Code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Code,
		&i.Type,
		&i.ValueMinor,
		&i.ValuePercent,
		&i.MaxUses,
		&i.ValidFrom,
		&i.ValidTo,
		&i.SingleUsePerEmail,
		&i.CreatedAt,
	)
	return i, err
}

const getCouponByCodeForUpdate = `-- name: GetCouponByCodeForUpdate :one
SELECT id, event_id, code, type, value_minor, value_percent, max_uses, valid_from, valid_to, single_use_per_email, created_at FROM coupons WHERE event_id = $1 AND code = $2 FOR UPDATE
`

type GetCouponByCodeForUpdateParams struct {
	EventID uuid.UUID
	Code    string
}

// Locks the coupon row inside a transaction so concurrent bookings can't
// both succeed past max_uses.
func (q *Queries) GetCouponByCodeForUpdate(ctx context.Context, arg GetCouponByCodeForUpdateParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByCodeForUpdate, arg.EventID, arg.Code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Code,
		&i.Type,
		&i.ValueMinor,
		&i.ValuePercent,
		&i.MaxUses,
		&i.ValidFrom,
		&i.ValidTo,
		&i.SingleUsePerEmail,
		&i.CreatedAt,
	)
	return i, err
}

const getDonationConfig = `-- name: GetDonationConfig :one

SELECT event_id, suggested_minor, min_minor FROM donation_configs WHERE event_id = $1
`

// ============================================================================
// Donation config
// ============================================================================
func (q *Queries) GetDonationConfig(ctx context.Context, eventID uuid.UUID) (DonationConfig, error) {
	row := q.db.QueryRow(ctx, getDonationConfig, eventID)
	var i DonationConfig
	err := row.Scan(&i.EventID, &i.SuggestedMinor, &i.MinMinor)
	return i, err
}

const getPriceCategory = `-- name: GetPriceCategory :one
SELECT id, event_id, name, ordering FROM price_categories WHERE id = $1
`

func (q *Queries) GetPriceCategory(ctx context.Context, id uuid.UUID) (PriceCategory, error) {
	row := q.db.QueryRow(ctx, getPriceCategory, id)
	var i PriceCategory
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Ordering,
	)
	return i, err
}

const getPriceDuration = `-- name: GetPriceDuration :one
SELECT id, event_id, name, ordering FROM price_durations WHERE id = $1
`

func (q *Queries) GetPriceDuration(ctx context.Context, id uuid.UUID) (PriceDuration, error) {
	row := q.db.QueryRow(ctx, getPriceDuration, id)
	var i PriceDuration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Ordering,
	)
	return i, err
}

const getPriceFor = `-- name: GetPriceFor :one
SELECT id, event_id, phase_id, category_id, duration_id, amount_minor FROM prices
WHERE phase_id = $1
  AND category_id = $2
  AND duration_id IS NOT DISTINCT FROM $3
LIMIT 1
`

type GetPriceForParams struct {
	PhaseID    uuid.UUID
	CategoryID uuid.UUID
	DurationID *uuid.UUID
}

// Looks up a price by (phase, category, duration). duration_id may be NULL
// in both query and stored row (events without duration dimension).
// IS NOT DISTINCT FROM is the null-safe equality operator.
func (q *Queries) GetPriceFor(ctx context.Context, arg GetPriceForParams) (Price, error) {
	row := q.db.QueryRow(ctx, getPriceFor, arg.PhaseID, arg.CategoryID, arg.DurationID)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PhaseID,
		&i.CategoryID,
		&i.DurationID,
		&i.AmountMinor,
	)
	return i, err
}

const getPricePhase = `-- name: GetPricePhase :one
SELECT id, event_id, name, starts_at, ends_at, ordering FROM price_phases WHERE id = $1
`

func (q *Queries) GetPricePhase(ctx context.Context, id uuid.UUID) (PricePhase, error) {
	row := q.db.QueryRow(ctx, getPricePhase, id)
	var i PricePhase
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.Ordering,
	)
	return i, err
}

const listCouponCategoryFilters = `-- name: ListCouponCategoryFilters :many
SELECT category_id FROM coupon_category_filters WHERE coupon_id = $1
`

func (q *Queries) ListCouponCategoryFilters(ctx context.Context, couponID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCouponCategoryFilters, couponID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var category_id uuid.UUID
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCouponPhaseFilters = `-- name: ListCouponPhaseFilters :many
SELECT phase_id FROM coupon_phase_filters WHERE coupon_id = $1
`

func (q *Queries) ListCouponPhaseFilters(ctx context.Context, couponID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCouponPhaseFilters, couponID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var phase_id uuid.UUID
		if err := rows.Scan(&phase_id); err != nil {
			return nil, err
		}
		items = append(items, phase_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoupons = `-- name: ListCoupons :many

SELECT id, event_id, code, type, value_minor, value_percent, max_uses, valid_from, valid_to, single_use_per_email, created_at FROM coupons WHERE event_id = $1 ORDER BY created_at
`

// ============================================================================
// Coupons
// ============================================================================
func (q *Queries) ListCoupons(ctx context.Context, eventID uuid.UUID) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, listCoupons, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coupon{}
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Code,
			&i.Type,
			&i.ValueMinor,
			&i.ValuePercent,
			&i.MaxUses,
			&i.ValidFrom,
			&i.ValidTo,
			&i.SingleUsePerEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceCategories = `-- name: ListPriceCategories :many

SELECT id, event_id, name, ordering FROM price_categories WHERE event_id = $1 ORDER BY ordering, name
`

// ============================================================================
// Categories
// ============================================================================
func (q *Queries) ListPriceCategories(ctx context.Context, eventID uuid.UUID) ([]PriceCategory, error) {
	rows, err := q.db.Query(ctx, listPriceCategories, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceCategory{}
	for rows.Next() {
		var i PriceCategory
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Ordering,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceDurations = `-- name: ListPriceDurations :many

SELECT id, event_id, name, ordering FROM price_durations WHERE event_id = $1 ORDER BY ordering, name
`

// ============================================================================
// Durations
// ============================================================================
func (q *Queries) ListPriceDurations(ctx context.Context, eventID uuid.UUID) ([]PriceDuration, error) {
	rows, err := q.db.Query(ctx, listPriceDurations, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceDuration{}
	for rows.Next() {
		var i PriceDuration
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Ordering,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricePhases = `-- name: ListPricePhases :many

SELECT id, event_id, name, starts_at, ends_at, ordering FROM price_phases WHERE event_id = $1 ORDER BY ordering, starts_at
`

// ============================================================================
// Phases
// ============================================================================
func (q *Queries) ListPricePhases(ctx context.Context, eventID uuid.UUID) ([]PricePhase, error) {
	rows, err := q.db.Query(ctx, listPricePhases, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricePhase{}
	for rows.Next() {
		var i PricePhase
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.StartsAt,
			&i.EndsAt,
			&i.Ordering,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrices = `-- name: ListPrices :many

SELECT id, event_id, phase_id, category_id, duration_id, amount_minor FROM prices WHERE event_id = $1
`

// ============================================================================
// Prices (sparse matrix cells)
// ============================================================================
func (q *Queries) ListPrices(ctx context.Context, eventID uuid.UUID) ([]Price, error) {
	rows, err := q.db.Query(ctx, listPrices, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Price{}
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.PhaseID,
			&i.CategoryID,
			&i.DurationID,
			&i.AmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCouponRedemption = `-- name: RecordCouponRedemption :exec
INSERT INTO coupon_redemptions (coupon_id, booking_id) VALUES ($1, $2)
`

type RecordCouponRedemptionParams struct {
	CouponID  uuid.UUID
	BookingID uuid.UUID
}

func (q *Queries) RecordCouponRedemption(ctx context.Context, arg RecordCouponRedemptionParams) error {
	_, err := q.db.Exec(ctx, recordCouponRedemption, arg.CouponID, arg.BookingID)
	return err
}

const updateCoupon = `-- name: UpdateCoupon :one
UPDATE coupons SET
    type = $2,
    value_minor = $3,
    value_percent = $4,
    max_uses = $5,
    valid_from = $6,
    valid_to = $7,
    single_use_per_email = $8
WHERE id = $1
RETURNING id, event_id, code, type, value_minor, value_percent, max_uses, valid_from, valid_to, single_use_per_email, created_at
`

type UpdateCouponParams struct {
	ID                uuid.UUID
	Type              string
	ValueMinor        *int64
	ValuePercent      *int32
	MaxUses           *int32
	ValidFrom         *time.Time
	ValidTo           *time.Time
	SingleUsePerEmail bool
}

func (q *Queries) UpdateCoupon(ctx context.Context, arg UpdateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, updateCoupon,
		arg.ID,
		arg.Type,
		arg.ValueMinor,
		arg.ValuePercent,
		arg.MaxUses,
		arg.ValidFrom,
		arg.ValidTo,
		arg.SingleUsePerEmail,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Code,
		&i.Type,
		&i.ValueMinor,
		&i.ValuePercent,
		&i.MaxUses,
		&i.ValidFrom,
		&i.ValidTo,
		&i.SingleUsePerEmail,
		&i.CreatedAt,
	)
	return i, err
}

const updatePriceCategory = `-- name: UpdatePriceCategory :one
UPDATE price_categories SET name = $2, ordering = $3 WHERE id = $1 RETURNING id, event_id, name, ordering
`

type UpdatePriceCategoryParams struct {
	ID       uuid.UUID
	Name     string
	Ordering int32
}

func (q *Queries) UpdatePriceCategory(ctx context.Context, arg UpdatePriceCategoryParams) (PriceCategory, error) {
	row := q.db.QueryRow(ctx, updatePriceCategory, arg.ID, arg.Name, arg.Ordering)
	var i PriceCategory
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Ordering,
	)
	return i, err
}

const updatePriceDuration = `-- name: UpdatePriceDuration :one
UPDATE price_durations SET name = $2, ordering = $3 WHERE id = $1 RETURNING id, event_id, name, ordering
`

type UpdatePriceDurationParams struct {
	ID       uuid.UUID
	Name     string
	Ordering int32
}

func (q *Queries) UpdatePriceDuration(ctx context.Context, arg UpdatePriceDurationParams) (PriceDuration, error) {
	row := q.db.QueryRow(ctx, updatePriceDuration, arg.ID, arg.Name, arg.Ordering)
	var i PriceDuration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Ordering,
	)
	return i, err
}

const updatePricePhase = `-- name: UpdatePricePhase :one
UPDATE price_phases SET
    name = $2, starts_at = $3, ends_at = $4, ordering = $5
WHERE id = $1
RETURNING id, event_id, name, starts_at, ends_at, ordering
`

type UpdatePricePhaseParams struct {
	ID       uuid.UUID
	Name     string
	StartsAt time.Time
	EndsAt   time.Time
	Ordering int32
}

func (q *Queries) UpdatePricePhase(ctx context.Context, arg UpdatePricePhaseParams) (PricePhase, error) {
	row := q.db.QueryRow(ctx, updatePricePhase,
		arg.ID,
		arg.Name,
		arg.StartsAt,
		arg.EndsAt,
		arg.Ordering,
	)
	var i PricePhase
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.Ordering,
	)
	return i, err
}

const upsertDonationConfig = `-- name: UpsertDonationConfig :one
INSERT INTO donation_configs (event_id, suggested_minor, min_minor)
VALUES ($1, $2, $3)
ON CONFLICT (event_id) DO UPDATE
SET suggested_minor = EXCLUDED.suggested_minor, min_minor = EXCLUDED.min_minor
RETURNING event_id, suggested_minor, min_minor
`

type UpsertDonationConfigParams struct {
	EventID        uuid.UUID
	SuggestedMinor int64
	MinMinor       int64
}

func (q *Queries) UpsertDonationConfig(ctx context.Context, arg UpsertDonationConfigParams) (DonationConfig, error) {
	row := q.db.QueryRow(ctx, upsertDonationConfig, arg.EventID, arg.SuggestedMinor, arg.MinMinor)
	var i DonationConfig
	err := row.Scan(&i.EventID, &i.SuggestedMinor, &i.MinMinor)
	return i, err
}

const upsertPrice = `-- name: UpsertPrice :one
INSERT INTO prices (event_id, phase_id, category_id, duration_id, amount_minor)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (phase_id, category_id, duration_id)
DO UPDATE SET amount_minor = EXCLUDED.amount_minor
RETURNING id, event_id, phase_id, category_id, duration_id, amount_minor
`

type UpsertPriceParams struct {
	EventID     uuid.UUID
	PhaseID     uuid.UUID
	CategoryID  uuid.UUID
	DurationID  *uuid.UUID
	AmountMinor int64
}

func (q *Queries) UpsertPrice(ctx context.Context, arg UpsertPriceParams) (Price, error) {
	row := q.db.QueryRow(ctx, upsertPrice,
		arg.EventID,
		arg.PhaseID,
		arg.CategoryID,
		arg.DurationID,
		arg.AmountMinor,
	)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PhaseID,
		&i.CategoryID,
		&i.DurationID,
		&i.AmountMinor,
	)
	return i, err
}
