// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: program_entries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProgramEntry = `-- name: CreateProgramEntry :one
INSERT INTO program_entries (event_id, starts_at, ends_at, title, description, ordering)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_id, starts_at, ends_at, title, description, ordering
`

type CreateProgramEntryParams struct {
	EventID     uuid.UUID
	StartsAt    time.Time
	EndsAt      *time.Time
	Title       string
	Description string
	Ordering    int32
}

func (q *Queries) CreateProgramEntry(ctx context.Context, arg CreateProgramEntryParams) (ProgramEntry, error) {
	row := q.db.QueryRow(ctx, createProgramEntry,
		arg.EventID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Title,
		arg.Description,
		arg.Ordering,
	)
	var i ProgramEntry
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Title,
		&i.Description,
		&i.Ordering,
	)
	return i, err
}

const deleteProgramEntry = `-- name: DeleteProgramEntry :exec
DELETE FROM program_entries WHERE id = $1
`

func (q *Queries) DeleteProgramEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProgramEntry, id)
	return err
}

const getProgramEntry = `-- name: GetProgramEntry :one
SELECT id, event_id, starts_at, ends_at, title, description, ordering FROM program_entries WHERE id = $1
`

func (q *Queries) GetProgramEntry(ctx context.Context, id uuid.UUID) (ProgramEntry, error) {
	row := q.db.QueryRow(ctx, getProgramEntry, id)
	var i ProgramEntry
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Title,
		&i.Description,
		&i.Ordering,
	)
	return i, err
}

const listProgramEntries = `-- name: ListProgramEntries :many
SELECT id, event_id, starts_at, ends_at, title, description, ordering FROM program_entries
WHERE event_id = $1
ORDER BY ordering ASC, starts_at ASC
`

func (q *Queries) ListProgramEntries(ctx context.Context, eventID uuid.UUID) ([]ProgramEntry, error) {
	rows, err := q.db.Query(ctx, listProgramEntries, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgramEntry{}
	for rows.Next() {
		var i ProgramEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Title,
			&i.Description,
			&i.Ordering,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgramEntry = `-- name: UpdateProgramEntry :one
UPDATE program_entries SET
    starts_at = $2,
    ends_at = $3,
    title = $4,
    description = $5,
    ordering = $6
WHERE id = $1
RETURNING id, event_id, starts_at, ends_at, title, description, ordering
`

type UpdateProgramEntryParams struct {
	ID          uuid.UUID
	StartsAt    time.Time
	EndsAt      *time.Time
	Title       string
	Description string
	Ordering    int32
}

func (q *Queries) UpdateProgramEntry(ctx context.Context, arg UpdateProgramEntryParams) (ProgramEntry, error) {
	row := q.db.QueryRow(ctx, updateProgramEntry,
		arg.ID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Title,
		arg.Description,
		arg.Ordering,
	)
	var i ProgramEntry
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Title,
		&i.Description,
		&i.Ordering,
	)
	return i, err
}
