// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, expires_at, user_agent, ip, password_version, impersonator_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, created_at, last_seen_at, expires_at, revoked_at, user_agent, ip, password_version, impersonator_user_id
`

type CreateSessionParams struct {
	ID                 []byte
	UserID             uuid.UUID
	ExpiresAt          time.Time
	UserAgent          *string
	Ip                 *netip.Addr
	PasswordVersion    int32
	ImpersonatorUserID *uuid.UUID
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
		arg.PasswordVersion,
		arg.ImpersonatorUserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
		&i.PasswordVersion,
		&i.ImpersonatorUserID,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at < now() OR revoked_at < now() - INTERVAL '7 days'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
    s.id,
    s.user_id,
    s.created_at,
    s.last_seen_at,
    s.expires_at,
    s.revoked_at,
    s.user_agent,
    s.ip,
    s.password_version AS session_password_version,
    s.impersonator_user_id,
    u.email            AS user_email,
    u.role             AS user_role,
    u.display_name     AS user_display_name,
    u.disabled_at      AS user_disabled_at,
    u.active           AS user_active,
    u.password_version AS user_password_version,
    imp.email          AS impersonator_email
FROM sessions s
JOIN users u ON u.id = s.user_id
LEFT JOIN users imp ON imp.id = s.impersonator_user_id
WHERE s.id = $1
`

type GetSessionByIDRow struct {
	ID                     []byte
	UserID                 uuid.UUID
	CreatedAt              time.Time
	LastSeenAt             time.Time
	ExpiresAt              time.Time
	RevokedAt              *time.Time
	UserAgent              *string
	Ip                     *netip.Addr
	SessionPasswordVersion int32
	ImpersonatorUserID     *uuid.UUID
	UserEmail              string
	UserRole               string
	UserDisplayName        *string
	UserDisabledAt         *time.Time
	UserActive             bool
	UserPasswordVersion    int32
	ImpersonatorEmail      *string
}

// The LEFT JOIN on the impersonator pulls the original actor's email when
// the session was minted via /admin/users/{id}/impersonate. Frontend uses
// this to show the "Du arbeitest gerade als …" banner; the impersonator's
// email never affects authorization (the middleware authorizes against
// u.role / u.id only).
func (q *Queries) GetSessionByID(ctx context.Context, id []byte) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
		&i.SessionPasswordVersion,
		&i.ImpersonatorUserID,
		&i.UserEmail,
		&i.UserRole,
		&i.UserDisplayName,
		&i.UserDisabledAt,
		&i.UserActive,
		&i.UserPasswordVersion,
		&i.ImpersonatorEmail,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
