// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelTicketByID = `-- name: CancelTicketByID :exec
UPDATE tickets
SET status = 'canceled', canceled_at = now()
WHERE id = $1 AND status IN ('booked', 'paid')
`

// Only cancels tickets currently in 'booked' or 'paid' state. CHECKED_IN
// tickets cannot be canceled by the holder; canceled tickets are a no-op.
func (q *Queries) CancelTicketByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelTicketByID, id)
	return err
}

const checkInTicket = `-- name: CheckInTicket :one
UPDATE tickets
SET status = 'checked_in',
    checked_in_at = COALESCE(checked_in_at, now()),
    paid_amount_minor = COALESCE(paid_amount_minor, $2::bigint)
WHERE id = $1
  AND status IN ('paid', 'checked_in')
RETURNING id, booking_id, participant_id, event_id, status, qr_token, phase_id, category_id, duration_id, amount_minor, created_at, paid_at, canceled_at, checked_in_at, qr_nonce, paid_amount_minor
`

type CheckInTicketParams struct {
	ID              uuid.UUID
	PaidAmountMinor *int64
}

// Idempotent door-scan. If the ticket is already checked_in we return the
// existing row unchanged (caller compares status before vs. after to decide
// whether to show "✓ checked in just now" or "⚠ already checked in at X").
// Only paid or already-checked-in tickets can be scanned; booked/canceled
// tickets don't match and the caller surfaces the right error.
//
// $2 is the door-collected amount: 0 / NULL for pre-paid tickets, a real
// number for at_door / donation tickets. Captured ONLY on the first scan —
// re-scans don't overwrite the previously recorded amount (COALESCE on the
// target column). To correct a mistyped amount, undo first then re-scan.
func (q *Queries) CheckInTicket(ctx context.Context, arg CheckInTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, checkInTicket, arg.ID, arg.PaidAmountMinor)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ParticipantID,
		&i.EventID,
		&i.Status,
		&i.QrToken,
		&i.PhaseID,
		&i.CategoryID,
		&i.DurationID,
		&i.AmountMinor,
		&i.CreatedAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CheckedInAt,
		&i.QrNonce,
		&i.PaidAmountMinor,
	)
	return i, err
}

const countCheckedInForEvent = `-- name: CountCheckedInForEvent :one
SELECT
    count(*) FILTER (WHERE status IN ('paid', 'checked_in'))::int AS expected,
    count(*) FILTER (WHERE status = 'checked_in')::int            AS checked_in
FROM tickets
WHERE event_id = $1
`

type CountCheckedInForEventRow struct {
	Expected  int32
	CheckedIn int32
}

func (q *Queries) CountCheckedInForEvent(ctx context.Context, eventID uuid.UUID) (CountCheckedInForEventRow, error) {
	row := q.db.QueryRow(ctx, countCheckedInForEvent, eventID)
	var i CountCheckedInForEventRow
	err := row.Scan(&i.Expected, &i.CheckedIn)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, booking_id, participant_id, event_id, status, qr_token, phase_id, category_id, duration_id, amount_minor, created_at, paid_at, canceled_at, checked_in_at, qr_nonce, paid_amount_minor FROM tickets WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ParticipantID,
		&i.EventID,
		&i.Status,
		&i.QrToken,
		&i.PhaseID,
		&i.CategoryID,
		&i.DurationID,
		&i.AmountMinor,
		&i.CreatedAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CheckedInAt,
		&i.QrNonce,
		&i.PaidAmountMinor,
	)
	return i, err
}

const getTicketWithContext = `-- name: GetTicketWithContext :one
SELECT
    t.id, t.booking_id, t.participant_id, t.event_id, t.status,
    t.qr_token, t.qr_nonce, t.amount_minor, t.paid_amount_minor,
    t.created_at, t.paid_at, t.canceled_at, t.checked_in_at,
    p.name AS participant_name, p.email AS participant_email,
    e.name AS event_name, e.slug AS event_slug,
    e.starts_at AS event_starts_at, e.ends_at AS event_ends_at,
    e.location AS event_location, e.currency AS event_currency,
    e.color_primary AS event_color_primary,
    e.color_secondary AS event_color_secondary,
    e.color_text AS event_color_text,
    e.pricing_mode AS event_pricing_mode,
    e.payment_timing AS event_payment_timing,
    ph.name AS phase_name,
    cat.name AS category_name,
    dur.name AS duration_name,
    b.contact_email AS booking_contact_email,
    b.payment_method AS booking_payment_method
FROM tickets t
JOIN participants p ON p.id = t.participant_id
JOIN events e ON e.id = t.event_id
JOIN bookings b ON b.id = t.booking_id
LEFT JOIN price_phases ph ON ph.id = t.phase_id
LEFT JOIN price_categories cat ON cat.id = t.category_id
LEFT JOIN price_durations dur ON dur.id = t.duration_id
WHERE t.id = $1
`

type GetTicketWithContextRow struct {
	ID                   uuid.UUID
	BookingID            uuid.UUID
	ParticipantID        uuid.UUID
	EventID              uuid.UUID
	Status               string
	QrToken              string
	QrNonce              []byte
	AmountMinor          int64
	PaidAmountMinor      *int64
	CreatedAt            time.Time
	PaidAt               *time.Time
	CanceledAt           *time.Time
	CheckedInAt          *time.Time
	ParticipantName      string
	ParticipantEmail     *string
	EventName            string
	EventSlug            string
	EventStartsAt        time.Time
	EventEndsAt          time.Time
	EventLocation        string
	EventCurrency        string
	EventColorPrimary    string
	EventColorSecondary  string
	EventColorText       string
	EventPricingMode     string
	EventPaymentTiming   string
	PhaseName            *string
	CategoryName         *string
	DurationName         *string
	BookingContactEmail  string
	BookingPaymentMethod *string
}

// Joins everything the public ticket page (and the door scanner) needs in
// one query. booking_payment_method drives the scanner's "ask for door
// cash" decision: ('donation', 'at_door') → show amount input.
func (q *Queries) GetTicketWithContext(ctx context.Context, id uuid.UUID) (GetTicketWithContextRow, error) {
	row := q.db.QueryRow(ctx, getTicketWithContext, id)
	var i GetTicketWithContextRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ParticipantID,
		&i.EventID,
		&i.Status,
		&i.QrToken,
		&i.QrNonce,
		&i.AmountMinor,
		&i.PaidAmountMinor,
		&i.CreatedAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CheckedInAt,
		&i.ParticipantName,
		&i.ParticipantEmail,
		&i.EventName,
		&i.EventSlug,
		&i.EventStartsAt,
		&i.EventEndsAt,
		&i.EventLocation,
		&i.EventCurrency,
		&i.EventColorPrimary,
		&i.EventColorSecondary,
		&i.EventColorText,
		&i.EventPricingMode,
		&i.EventPaymentTiming,
		&i.PhaseName,
		&i.CategoryName,
		&i.DurationName,
		&i.BookingContactEmail,
		&i.BookingPaymentMethod,
	)
	return i, err
}

const listActiveTicketsForBooking = `-- name: ListActiveTicketsForBooking :many
SELECT id, booking_id, participant_id, event_id, status, qr_token, phase_id, category_id, duration_id, amount_minor, created_at, paid_at, canceled_at, checked_in_at, qr_nonce, paid_amount_minor FROM tickets
WHERE booking_id = $1 AND status IN ('booked', 'paid', 'checked_in')
`

func (q *Queries) ListActiveTicketsForBooking(ctx context.Context, bookingID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listActiveTicketsForBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.ParticipantID,
			&i.EventID,
			&i.Status,
			&i.QrToken,
			&i.PhaseID,
			&i.CategoryID,
			&i.DurationID,
			&i.AmountMinor,
			&i.CreatedAt,
			&i.PaidAt,
			&i.CanceledAt,
			&i.CheckedInAt,
			&i.QrNonce,
			&i.PaidAmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCheckInsForEvent = `-- name: ListRecentCheckInsForEvent :many
SELECT
    t.id, t.checked_in_at, t.paid_amount_minor,
    p.name AS participant_name,
    p.email AS participant_email,
    upper(substring(replace(b.id::text, '-', '') from 1 for 8)) AS booking_reference
FROM tickets t
JOIN participants p ON p.id = t.participant_id
JOIN bookings b ON b.id = t.booking_id
WHERE t.event_id = $1 AND t.status = 'checked_in' AND t.checked_in_at IS NOT NULL
ORDER BY t.checked_in_at DESC
LIMIT $2
`

type ListRecentCheckInsForEventParams struct {
	EventID uuid.UUID
	Limit   int32
}

type ListRecentCheckInsForEventRow struct {
	ID               uuid.UUID
	CheckedInAt      *time.Time
	PaidAmountMinor  *int64
	ParticipantName  string
	ParticipantEmail *string
	BookingReference interface{}
}

// Most recent N check-ins, used by the scanner page to show a live log so
// door staff can spot mistakes ("oh I scanned the wrong person"). Includes
// the recorded paid_amount_minor (= cash collected at the door) for the
// few-row "Rückgängig" affordance.
func (q *Queries) ListRecentCheckInsForEvent(ctx context.Context, arg ListRecentCheckInsForEventParams) ([]ListRecentCheckInsForEventRow, error) {
	rows, err := q.db.Query(ctx, listRecentCheckInsForEvent, arg.EventID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentCheckInsForEventRow{}
	for rows.Next() {
		var i ListRecentCheckInsForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.CheckedInAt,
			&i.PaidAmountMinor,
			&i.ParticipantName,
			&i.ParticipantEmail,
			&i.BookingReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchActiveTicketsForEvent = `-- name: SearchActiveTicketsForEvent :many
SELECT
    t.id, t.status, t.checked_in_at,
    p.name AS participant_name,
    p.email AS participant_email,
    b.id AS booking_id,
    b.contact_name AS contact_name,
    b.contact_email AS contact_email
FROM tickets t
JOIN participants p ON p.id = t.participant_id
JOIN bookings b ON b.id = t.booking_id
WHERE t.event_id = $1
  AND t.status IN ('paid', 'checked_in')
  AND (
       lower(p.name) LIKE '%' || lower($2::text) || '%'
    OR lower(b.contact_name) LIKE '%' || lower($2::text) || '%'
    OR lower(COALESCE(p.email, '')) LIKE '%' || lower($2::text) || '%'
    OR lower(b.contact_email) LIKE '%' || lower($2::text) || '%'
    OR upper(substring(replace(b.id::text, '-', '') from 1 for 8)) LIKE upper('%' || $2::text || '%')
  )
ORDER BY p.name ASC
LIMIT 25
`

type SearchActiveTicketsForEventParams struct {
	EventID uuid.UUID
	Column2 string
}

type SearchActiveTicketsForEventRow struct {
	ID               uuid.UUID
	Status           string
	CheckedInAt      *time.Time
	ParticipantName  string
	ParticipantEmail *string
	BookingID        uuid.UUID
	ContactName      string
	ContactEmail     string
}

// Manual check-in fallback. Accepts a free-text query and ILIKE-matches
// across participant name + email, booking contact name + email, AND the
// booking-reference prefix (first 8 hex of the booking UUID). Scoped to
// the event so a manager can't accidentally pull tickets from another
// event with overlapping data.
//
// One row per *participant* (= per ticket) — the scanner lists them and
// the staffer taps a single person to check in. LIMIT 25 caps the
// response; typing more characters narrows the list.
func (q *Queries) SearchActiveTicketsForEvent(ctx context.Context, arg SearchActiveTicketsForEventParams) ([]SearchActiveTicketsForEventRow, error) {
	rows, err := q.db.Query(ctx, searchActiveTicketsForEvent, arg.EventID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchActiveTicketsForEventRow{}
	for rows.Next() {
		var i SearchActiveTicketsForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CheckedInAt,
			&i.ParticipantName,
			&i.ParticipantEmail,
			&i.BookingID,
			&i.ContactName,
			&i.ContactEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferTicket = `-- name: TransferTicket :exec
UPDATE tickets
SET qr_nonce = $2, qr_token = $3
WHERE id = $1
`

type TransferTicketParams struct {
	ID      uuid.UUID
	QrNonce []byte
	QrToken string
}

// Atomic transfer: rotates qr_nonce and qr_token, plus updates the
// participant row that's joined to this ticket via participant_id.
func (q *Queries) TransferTicket(ctx context.Context, arg TransferTicketParams) error {
	_, err := q.db.Exec(ctx, transferTicket, arg.ID, arg.QrNonce, arg.QrToken)
	return err
}

const undoCheckInTicket = `-- name: UndoCheckInTicket :one
UPDATE tickets
SET status = 'paid',
    checked_in_at = NULL,
    paid_amount_minor = NULL
WHERE id = $1
  AND status = 'checked_in'
RETURNING id, booking_id, participant_id, event_id, status, qr_token, phase_id, category_id, duration_id, amount_minor, created_at, paid_at, canceled_at, checked_in_at, qr_nonce, paid_amount_minor
`

// Reverses an accidental check-in: clears checked_in_at + paid_amount_minor
// and flips status back to 'paid'. Audit-logged at the handler. Only works
// on currently-checked-in tickets (no-op otherwise).
func (q *Queries) UndoCheckInTicket(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, undoCheckInTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ParticipantID,
		&i.EventID,
		&i.Status,
		&i.QrToken,
		&i.PhaseID,
		&i.CategoryID,
		&i.DurationID,
		&i.AmountMinor,
		&i.CreatedAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CheckedInAt,
		&i.QrNonce,
		&i.PaidAmountMinor,
	)
	return i, err
}

const updateParticipantContact = `-- name: UpdateParticipantContact :exec
UPDATE participants
SET name = $2, email = $3
WHERE id = $1
`

type UpdateParticipantContactParams struct {
	ID    uuid.UUID
	Name  string
	Email *string
}

func (q *Queries) UpdateParticipantContact(ctx context.Context, arg UpdateParticipantContactParams) error {
	_, err := q.db.Exec(ctx, updateParticipantContact, arg.ID, arg.Name, arg.Email)
	return err
}
