// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpPasswordVersion = `-- name: BumpPasswordVersion :exec
UPDATE users SET password_version = password_version + 1 WHERE id = $1
`

// Force-logout: bump the user's password_version without touching the hash.
func (q *Queries) BumpPasswordVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpPasswordVersion, id)
	return err
}

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :exec
UPDATE password_reset_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumePasswordResetToken, id)
	return err
}

const consumeSetupToken = `-- name: ConsumeSetupToken :exec
UPDATE setup_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) ConsumeSetupToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeSetupToken, id)
	return err
}

const invalidateOutstandingSetupTokensForUser = `-- name: InvalidateOutstandingSetupTokensForUser :exec
UPDATE setup_tokens
SET used_at = now()
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) InvalidateOutstandingSetupTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateOutstandingSetupTokensForUser, userID)
	return err
}

const countGlobalAdmins = `-- name: CountGlobalAdmins :one
SELECT count(*)::int AS n
FROM users
WHERE role = 'global_admin' AND disabled_at IS NULL
`

func (q *Queries) CountGlobalAdmins(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countGlobalAdmins)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const countSessionsForUser = `-- name: CountSessionsForUser :one
SELECT count(*)::int AS n FROM sessions WHERE user_id = $1 AND expires_at > now()
`

func (q *Queries) CountSessionsForUser(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countSessionsForUser, userID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const createInvitedUser = `-- name: CreateInvitedUser :one
INSERT INTO users (email, password_hash, role, display_name, active)
VALUES ($1, $2, $3, $4, false)
RETURNING id, email, password_hash, role, display_name, created_at, disabled_at, password_version, active, last_login_at
`

type CreateInvitedUserParams struct {
	Email        string
	PasswordHash string
	Role         string
	DisplayName  *string
}

// Used by the invite flow. password_hash is a placeholder (random bytes,
// argon2id-hashed). active=false until the invitee completes setup.
func (q *Queries) CreateInvitedUser(ctx context.Context, arg CreateInvitedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createInvitedUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.PasswordVersion,
		&i.Active,
		&i.LastLoginAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSetupToken = `-- name: CreateSetupToken :one
INSERT INTO setup_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreateSetupTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateSetupToken(ctx context.Context, arg CreateSetupTokenParams) (SetupToken, error) {
	row := q.db.QueryRow(ctx, createSetupToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i SetupToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, role, display_name, created_at, disabled_at, password_version, active, last_login_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Role         string
	DisplayName  *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.PasswordVersion,
		&i.Active,
		&i.LastLoginAt,
	)
	return i, err
}

const disableUser = `-- name: DisableUser :exec
UPDATE users SET disabled_at = now() WHERE id = $1 AND disabled_at IS NULL
`

func (q *Queries) DisableUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableUser, id)
	return err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM password_reset_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSetupTokenByHash = `-- name: GetSetupTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM setup_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetSetupTokenByHash(ctx context.Context, tokenHash string) (SetupToken, error) {
	row := q.db.QueryRow(ctx, getSetupTokenByHash, tokenHash)
	var i SetupToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, display_name, created_at, disabled_at, password_version, active, last_login_at FROM users
WHERE lower(email) = lower($1) AND disabled_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.PasswordVersion,
		&i.Active,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, display_name, created_at, disabled_at, password_version, active, last_login_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.PasswordVersion,
		&i.Active,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, role, display_name, active, created_at, disabled_at, last_login_at
FROM users
ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID          uuid.UUID
	Email       string
	Role        string
	DisplayName *string
	Active      bool
	CreatedAt   time.Time
	DisabledAt  *time.Time
	LastLoginAt *time.Time
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.DisplayName,
			&i.Active,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateUser = `-- name: ReactivateUser :exec
UPDATE users SET disabled_at = NULL, active = true WHERE id = $1
`

func (q *Queries) ReactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, reactivateUser, id)
	return err
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET active = $2 WHERE id = $1
`

type SetUserActiveParams struct {
	ID     uuid.UUID
	Active bool
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.ID, arg.Active)
	return err
}

const setUserPasswordAndActivate = `-- name: SetUserPasswordAndActivate :exec
UPDATE users
SET password_hash = $2, active = true, password_version = password_version + 1
WHERE id = $1
`

type SetUserPasswordAndActivateParams struct {
	ID           uuid.UUID
	PasswordHash string
}

// One-shot used by the setup-token flow: writes the new hash, marks the
// user active, bumps password_version (so any pre-setup session is killed).
func (q *Queries) SetUserPasswordAndActivate(ctx context.Context, arg SetUserPasswordAndActivateParams) error {
	_, err := q.db.Exec(ctx, setUserPasswordAndActivate, arg.ID, arg.PasswordHash)
	return err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users SET role = $2 WHERE id = $1
`

type SetUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ID, arg.Role)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchUserLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users SET display_name = $2 WHERE id = $1
`

type UpdateUserDisplayNameParams struct {
	ID          uuid.UUID
	DisplayName *string
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, password_version = password_version + 1 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

// Updates the password hash AND bumps password_version, which kills every
// outstanding session for the user (sessions remember the version they were
// minted at; the auth middleware rejects mismatches).
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
