// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waitlist.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countWaitingForEvent = `-- name: CountWaitingForEvent :one
SELECT count(*)::int AS waiting
FROM waitlist_entries
WHERE event_id = $1 AND status = 'waiting'
`

func (q *Queries) CountWaitingForEvent(ctx context.Context, eventID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countWaitingForEvent, eventID)
	var waiting int32
	err := row.Scan(&waiting)
	return waiting, err
}

const createWaitlistEntry = `-- name: CreateWaitlistEntry :one
INSERT INTO waitlist_entries (
    event_id, contact_email, contact_name, locale, requested_seats,
    selection_json, coupon_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, event_id, contact_email, contact_name, locale, requested_seats, selection_json, created_at, promoted_at, claim_deadline, fulfilled_booking_id, status, coupon_id
`

type CreateWaitlistEntryParams struct {
	EventID        uuid.UUID
	ContactEmail   string
	ContactName    string
	Locale         string
	RequestedSeats int32
	SelectionJson  []byte
	CouponID       *uuid.UUID
}

func (q *Queries) CreateWaitlistEntry(ctx context.Context, arg CreateWaitlistEntryParams) (WaitlistEntry, error) {
	row := q.db.QueryRow(ctx, createWaitlistEntry,
		arg.EventID,
		arg.ContactEmail,
		arg.ContactName,
		arg.Locale,
		arg.RequestedSeats,
		arg.SelectionJson,
		arg.CouponID,
	)
	var i WaitlistEntry
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ContactEmail,
		&i.ContactName,
		&i.Locale,
		&i.RequestedSeats,
		&i.SelectionJson,
		&i.CreatedAt,
		&i.PromotedAt,
		&i.ClaimDeadline,
		&i.FulfilledBookingID,
		&i.Status,
		&i.CouponID,
	)
	return i, err
}

const getWaitlistEntryByID = `-- name: GetWaitlistEntryByID :one
SELECT id, event_id, contact_email, contact_name, locale, requested_seats, selection_json, created_at, promoted_at, claim_deadline, fulfilled_booking_id, status, coupon_id FROM waitlist_entries WHERE id = $1
`

func (q *Queries) GetWaitlistEntryByID(ctx context.Context, id uuid.UUID) (WaitlistEntry, error) {
	row := q.db.QueryRow(ctx, getWaitlistEntryByID, id)
	var i WaitlistEntry
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ContactEmail,
		&i.ContactName,
		&i.Locale,
		&i.RequestedSeats,
		&i.SelectionJson,
		&i.CreatedAt,
		&i.PromotedAt,
		&i.ClaimDeadline,
		&i.FulfilledBookingID,
		&i.Status,
		&i.CouponID,
	)
	return i, err
}

const listExpiredPromotedWaitlist = `-- name: ListExpiredPromotedWaitlist :many
SELECT id, event_id FROM waitlist_entries
WHERE status = 'promoted'
  AND claim_deadline IS NOT NULL
  AND claim_deadline < now()
`

type ListExpiredPromotedWaitlistRow struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

// Sweeper input: waitlist rows whose claim window has passed. The reservation
// expiry sweeper cancels the underlying booking; this query lets the waitlist
// service mark the row 'expired' and trigger re-promotion.
func (q *Queries) ListExpiredPromotedWaitlist(ctx context.Context) ([]ListExpiredPromotedWaitlistRow, error) {
	rows, err := q.db.Query(ctx, listExpiredPromotedWaitlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredPromotedWaitlistRow{}
	for rows.Next() {
		var i ListExpiredPromotedWaitlistRow
		if err := rows.Scan(&i.ID, &i.EventID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingForEventLocking = `-- name: ListWaitingForEventLocking :many
SELECT id, event_id, contact_email, contact_name, locale, requested_seats, selection_json, created_at, promoted_at, claim_deadline, fulfilled_booking_id, status, coupon_id FROM waitlist_entries
WHERE event_id = $1 AND status = 'waiting'
ORDER BY created_at ASC
FOR UPDATE
`

// FIFO scan of the queue, locked for promotion. Caller MUST run inside the
// same transaction that took the event-row lock via LockEventForCapacity,
// so the lock ordering is consistent (event row first, then waitlist rows)
// and concurrent promote attempts serialize cleanly.
func (q *Queries) ListWaitingForEventLocking(ctx context.Context, eventID uuid.UUID) ([]WaitlistEntry, error) {
	rows, err := q.db.Query(ctx, listWaitingForEventLocking, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaitlistEntry{}
	for rows.Next() {
		var i WaitlistEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ContactEmail,
			&i.ContactName,
			&i.Locale,
			&i.RequestedSeats,
			&i.SelectionJson,
			&i.CreatedAt,
			&i.PromotedAt,
			&i.ClaimDeadline,
			&i.FulfilledBookingID,
			&i.Status,
			&i.CouponID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitlistForEvent = `-- name: ListWaitlistForEvent :many
SELECT id, event_id, contact_email, contact_name, locale, requested_seats, selection_json, created_at, promoted_at, claim_deadline, fulfilled_booking_id, status, coupon_id FROM waitlist_entries
WHERE event_id = $1
ORDER BY created_at ASC
`

// Admin view: every status, every row.
func (q *Queries) ListWaitlistForEvent(ctx context.Context, eventID uuid.UUID) ([]WaitlistEntry, error) {
	rows, err := q.db.Query(ctx, listWaitlistForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaitlistEntry{}
	for rows.Next() {
		var i WaitlistEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ContactEmail,
			&i.ContactName,
			&i.Locale,
			&i.RequestedSeats,
			&i.SelectionJson,
			&i.CreatedAt,
			&i.PromotedAt,
			&i.ClaimDeadline,
			&i.FulfilledBookingID,
			&i.Status,
			&i.CouponID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEventForCapacity = `-- name: LockEventForCapacity :exec
SELECT id FROM events WHERE id = $1 FOR UPDATE
`

// Bare row-lock on the event. Pair this with CountActiveSeatsForEvent (no
// locking variant) inside the same tx so capacity reads are stable.
func (q *Queries) LockEventForCapacity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockEventForCapacity, id)
	return err
}

const markWaitlistExpired = `-- name: MarkWaitlistExpired :exec
UPDATE waitlist_entries
SET status = 'expired'
WHERE id = $1 AND status = 'promoted'
`

func (q *Queries) MarkWaitlistExpired(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWaitlistExpired, id)
	return err
}

const markWaitlistFulfilled = `-- name: MarkWaitlistFulfilled :exec
UPDATE waitlist_entries
SET status = 'fulfilled', fulfilled_booking_id = $2
WHERE id = $1 AND status IN ('waiting', 'promoted')
`

type MarkWaitlistFulfilledParams struct {
	ID                 uuid.UUID
	FulfilledBookingID *uuid.UUID
}

func (q *Queries) MarkWaitlistFulfilled(ctx context.Context, arg MarkWaitlistFulfilledParams) error {
	_, err := q.db.Exec(ctx, markWaitlistFulfilled, arg.ID, arg.FulfilledBookingID)
	return err
}

const markWaitlistPromoted = `-- name: MarkWaitlistPromoted :exec
UPDATE waitlist_entries
SET status = 'promoted', promoted_at = now(), claim_deadline = $2
WHERE id = $1 AND status = 'waiting'
`

type MarkWaitlistPromotedParams struct {
	ID            uuid.UUID
	ClaimDeadline *time.Time
}

func (q *Queries) MarkWaitlistPromoted(ctx context.Context, arg MarkWaitlistPromotedParams) error {
	_, err := q.db.Exec(ctx, markWaitlistPromoted, arg.ID, arg.ClaimDeadline)
	return err
}

const markWaitlistRemoved = `-- name: MarkWaitlistRemoved :exec
UPDATE waitlist_entries
SET status = 'removed'
WHERE id = $1 AND status NOT IN ('fulfilled', 'removed')
`

func (q *Queries) MarkWaitlistRemoved(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWaitlistRemoved, id)
	return err
}

const positionInWaitlist = `-- name: PositionInWaitlist :one
SELECT (count(*)::int + 1) AS position
FROM waitlist_entries w
WHERE w.event_id = $1
  AND w.status = 'waiting'
  AND w.created_at < (SELECT w2.created_at FROM waitlist_entries w2 WHERE w2.id = $2)
`

type PositionInWaitlistParams struct {
	EventID uuid.UUID
	ID      uuid.UUID
}

// 1-based position of the given waiter among current waiting rows.
func (q *Queries) PositionInWaitlist(ctx context.Context, arg PositionInWaitlistParams) (int32, error) {
	row := q.db.QueryRow(ctx, positionInWaitlist, arg.EventID, arg.ID)
	var position int32
	err := row.Scan(&position)
	return position, err
}

const waitlistStatusCountsForEvent = `-- name: WaitlistStatusCountsForEvent :one
SELECT
    count(*) FILTER (WHERE status = 'waiting')::int   AS waiting_count,
    count(*) FILTER (WHERE status = 'promoted')::int  AS promoted_count,
    count(*) FILTER (WHERE status = 'fulfilled')::int AS fulfilled_count,
    count(*) FILTER (WHERE status = 'expired')::int   AS expired_count,
    count(*) FILTER (WHERE status = 'removed')::int   AS removed_count
FROM waitlist_entries
WHERE event_id = $1
`

type WaitlistStatusCountsForEventRow struct {
	WaitingCount   int32
	PromotedCount  int32
	FulfilledCount int32
	ExpiredCount   int32
	RemovedCount   int32
}

func (q *Queries) WaitlistStatusCountsForEvent(ctx context.Context, eventID uuid.UUID) (WaitlistStatusCountsForEventRow, error) {
	row := q.db.QueryRow(ctx, waitlistStatusCountsForEvent, eventID)
	var i WaitlistStatusCountsForEventRow
	err := row.Scan(
		&i.WaitingCount,
		&i.PromotedCount,
		&i.FulfilledCount,
		&i.ExpiredCount,
		&i.RemovedCount,
	)
	return i, err
}
